blank_issues_enabled: true
contact_links:
    - name: Feature Request
      url: https://github.com/yannelli/dosespot-php/issues/new?title=%5BFeature%5D%3A%20
      about: Share ideas for new features
    - name: Ask a Question
      url: https://github.com/yannelli/dosespot-php/issues/new?title=%5BQuestion%5D%3A%20
      about: Ask the community for help
